import psutil
import platform
print(f"\n\n")
print(f"Sistem Operasi: {platform.system()}")
print(f"Nama Mesin: {platform.node()}")
print(f"Rilis OS: {platform.release()}")
print(f"Versi OS: {platform.version()}")
print(f"Arsitektur: {platform.machine()}")
print(f"Prosesor: {platform.processor()}")
print(f"Platform Lengkap: {platform.platform()}")
print(f"\n\n")
ram = psutil.virtual_memory()
print(f"RAM Total: {ram.total / (1024**3):.2f} GB")
print(f"Memori Tersedia: {ram.available / (1024**3):.2f} GB")
print(f"Persentase Penggunaan Memori: {ram.percent}%")
print(f"\n\n")
print(f"Penggunaan CPU Saat Ini: {psutil.cpu_percent(interval=1)}%")
print(f"Jumlah Core CPU: {psutil.cpu_count(logical=False)} (Fisik)")
print(f"Jumlah Logical CPU: {psutil.cpu_count(logical=True)} (Logis)")
print(f"\n\n")